# -*- coding: utf-8 -*-
"""
Module: talos_service_api.py (v1.0)
Project: TALOS v5.9.15
Description:
    Micro-Flask API server for the TALOS Autonomous Research Service.
    Provides a lightweight HTTP interface to query the service's status,
    daily discoveries, and reports without interfering with the
    background research process.

    Endpoints:
    - GET /api/status   → service uptime, papers found, DB stats
    - GET /api/report   → today's HTML report

    Key design decisions:
    - Uses port 5002 (doesn't conflict with dashboard:5000 or GUI:8501)
    - All data is read from static files (reports/argus/YYYY-MM-DD/)
      generated by talos_service.py — no direct DB access needed.
    - Single-file, minimal dependencies, starts in <1 second.

    Usage:
        python src/api/talos_service_api.py
"""
import os
import sys
import os, sys
_P = os.path.abspath(os.path.dirname(__file__))
while _P and not os.path.exists(os.path.join(_P, 'talos.py')):
    _P = os.path.dirname(_P)
if _P: sys.path.insert(0, _P)
import json
from datetime import datetime
from pathlib import Path
from flask import Flask, jsonify

# ── Add project root to Python's import path ────────────────────────────────
app = Flask(__name__)

# ── Report root directory ───────────────────────────────────────────────────
REPORTS_ROOT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "data", "reports", "argus"
)


def _get_today_folder():
    """Return the path to today's report folder."""
    today = datetime.now().strftime("%Y-%m-%d")
    return os.path.join(REPORTS_ROOT, today)


@app.route("/api/status")
def api_status():
    """Return service status including uptime and today's discoveries.

    Returns:
        JSON with uptime, papers_found_today, high_score_count, db_stats.
    """
    today_folder = _get_today_folder()
    discoveries = []

    # ── Read today's discoveries if available ────────────────────────────
    json_path = os.path.join(today_folder, "discoveries.json")
    if os.path.exists(json_path):
        try:
            with open(json_path, "r") as f:
                discoveries = json.load(f)
        except Exception:
            pass

    # ── Read DB stats ────────────────────────────────────────────────────
    stats = {"total": 0, "elite": 0, "avg_score": 0.0}
    try:
        import sqlite3
        project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        db_path = os.path.join(project_root, "data", "talos_research.db")
        if not os.path.exists(db_path):
            profile_db = os.path.join(project_root, "_profiles", "default_drones", "talos_research.db")
            if os.path.exists(profile_db):
                db_path = profile_db
        with sqlite3.connect(db_path) as conn:
            c = conn.cursor()
            c.execute("SELECT COUNT(*) FROM papers WHERE overall_score IS NOT NULL AND overall_score > 0")
            stats["total"] = c.fetchone()[0]
            c.execute("SELECT COUNT(*) FROM papers WHERE overall_score >= 8")
            stats["elite"] = c.fetchone()[0]
            c.execute("SELECT AVG(overall_score) FROM papers WHERE overall_score IS NOT NULL AND overall_score > 0")
            avg = c.fetchone()[0]
            stats["avg_score"] = round(avg, 2) if avg else 0.0
    except Exception:
        pass

    return jsonify({
        "status": "running",
        "date": datetime.now().strftime("%Y-%m-%d"),
        "time": datetime.now().strftime("%H:%M:%S"),
        "papers_found_today": len(discoveries),
        "high_score_papers": [d for d in discoveries if d.get("score", 0) >= 8],
        "db_stats": stats,
    })


@app.route("/api/report")
def api_report():
    """Return today's HTML report as a web page."""
    today_folder = _get_today_folder()
    html_path = os.path.join(today_folder, "report.html")
    if os.path.exists(html_path):
        with open(html_path, "r", encoding="utf-8") as f:
            return f.read()
    return f"<h2>No report generated yet for {datetime.now().strftime('%Y-%m-%d')}</h2>", 404


if __name__ == "__main__":
    print("=" * 50)
    print("  TALOS Service API — v5.0.0")
    print(f"  Open: http://localhost:5002/api/status")
    print("=" * 50)
    app.run(host="127.0.0.1", port=5002, debug=False)