# -*- coding: utf-8 -*-
"""
Module: daemon_autostart.py
Project: TALOS v5.25.3
Description:
    Windows OS autostart orchestrator for the TALOS 24/7 autonomous daemon.
    Generates a self-contained boot batch script (talos_daemon_boot.bat) that
    provisions the conda environment, conditionally starts the local Fast Edge
    CPU server, and launches the daemon. It then registers a Windows
    Startup-folder shortcut (via pywin32 Shell COM) so the daemon survives
    reboots with a minimized console and a system icon.

    v5.18.2 adds an interactive research-profile target selector: the operator
    chooses which profile the 24/7 daemon activates on boot, and the selected
    profile is embedded as a ``--profile <name>`` argument in both the boot
    batch script and the Startup shortcut so the daemon boots into the correct
    isolated workspace SSOT.

    v5.18.3 confirms this selector as the canonical daemon-profile provisioning
    path: the selected profile is embedded into the generated boot batch and
    Startup shortcut, and the daemon banner and execution dynamically
    synchronize to it via ``talos_service.py --profile <name>``.

    v5.18.5 promotes profile selection to the first mandatory prompt of a new
    ``main()`` provisioning flow, adopts the canonical ``TALOS_QUESTIONARY_STYLE``
    theme, cancels cleanly on Ctrl+C without mutating autostart state, and
    persists the selected daemon target into ``_profiles/<profile>/config.json``.

    Key design decisions:
    - The generated .bat is human-auditable and lives at the project root.
    - pywin32 (win32com.client) is imported lazily inside the installer so
      this module remains importable on non-Windows platforms.
    - All shell operations are wrapped in try/except so a missing dependency
      or a missing Startup folder degrades gracefully with a clear message.

Dependencies:
    - os, pathlib: Filesystem and path resolution.
    - win32com.client (pywin32): Windows Shell COM shortcut creation (lazy).
"""
import json
import os
import sys
from pathlib import Path


SHORTCUT_NAME = "TALOS Autonomous Daemon"


def _project_root():
    """Resolve the absolute project root (parent of src/)."""
    return str(Path(__file__).resolve().parent.parent.parent)


def generate_boot_batch(profile_name=None):
    """Generate talos_daemon_boot.bat in the project root.

    The batch script sets a clean console and launches the daemon against the
    unified local AI runtime (port 11434). All Python invocations use the
    absolute path of the current interpreter (sys.executable, quoted) so the
    correct conda environment is always used without relying on PATH.

    When ``profile_name`` is supplied (v5.18.2), a ``--profile <name>``
    argument is appended to the daemon invocation so the boot-time daemon
    activates the operator-selected research profile SSOT.

    Args:
        profile_name (str, optional): Target research profile for the daemon.

    Returns:
        str: Absolute path to the generated batch script.
    """
    root = _project_root()
    bat_path = os.path.join(root, "talos_daemon_boot.bat")
    py = '"' + sys.executable + '"'
    lines = [
        "@echo off",
        "mode con: cols=120 lines=30",
        "title TALOS Autonomous Research Daemon",
        'cd /d "%~dp0"',
        "",
        "REM -------------------------------------------------------------------",
        "REM TALOS Daemon Boot Script (generated by src/utils/daemon_autostart.py)",
        "REM -------------------------------------------------------------------",
        "",
        "REM 1. Launch the 24/7 autonomous research daemon.",
        py + ' src/ai/drl/talos_service.py' + (
            ' --profile ' + profile_name if profile_name else ''
        ),
    ]
    with open(bat_path, "w", encoding="utf-8", newline="") as f:
        f.write(os.linesep.join(lines) + os.linesep)
    return bat_path


def select_daemon_profile():
    """Prompt the operator to choose the target research profile for the daemon.

    Queries ``ProfileManager().list_profiles()`` and renders a questionary
    select prompt (canonical ``TALOS_QUESTIONARY_STYLE``) defaulting to the
    current active profile. When no profiles exist, the active profile is
    returned; when questionary is unavailable (for example a headless boot),
    the active profile is returned as-is. A Ctrl+C cancel returns ``None`` so
    callers can exit without mutating autostart state.

    Returns:
        str | None: The selected profile name, or None when cancelled.
    """
    try:
        from src.core.profile_manager import ProfileManager
        pm = ProfileManager()
        profiles = pm.list_profiles()
        active = pm.get_active_profile_name()
    except Exception:
        return "default"

    if not profiles:
        return active or "default"

    try:
        import questionary
        from src.utils.ui_theme import TALOS_QUESTIONARY_STYLE
    except Exception:
        return active or "default"

    if active and active not in profiles:
        profiles.insert(0, active)
    default_choice = active if active in profiles else (profiles[0] if profiles else "default")

    try:
        choice = questionary.select(
            "Select target research profile for the 24/7 background daemon:",
            choices=profiles,
            default=default_choice,
            style=TALOS_QUESTIONARY_STYLE,
        ).ask()
    except KeyboardInterrupt:
        return None
    except Exception:
        return active or "default"

    return choice or None


def install_windows_autostart(profile_name=None):
    """Install the TALOS daemon into the Windows Startup folder.

    Generates talos_daemon_boot.bat and creates a .lnk shortcut named
    "TALOS Autonomous Daemon" in the user's Startup folder with a system
    icon (shell32.dll) and a minimized window style. When ``profile_name``
    is supplied (v5.18.2), the selected research profile is embedded as a
    ``--profile <name>`` argument in both the boot batch and the shortcut.

    Args:
        profile_name (str, optional): Target research profile for the daemon.

    Returns:
        str | None: Path to the created shortcut, the boot batch path if the
            shortcut could not be created, or None on failure.
    """
    bat_path = generate_boot_batch(profile_name=profile_name)
    try:
        import win32com.client
    except ImportError:
        print("  [WARN] pywin32 not installed -- Startup shortcut not created.")
        print(f"  [INFO] Boot script generated at: {bat_path}")
        return None

    appdata = os.environ.get("APPDATA", "")
    startup_dir = os.path.join(
        appdata, "Microsoft", "Windows", "Start Menu", "Programs", "Startup")
    if not appdata or not os.path.isdir(os.path.dirname(startup_dir)):
        print("  [WARN] Startup folder not found -- shortcut not created.")
        return bat_path

    shortcut_path = os.path.join(startup_dir, SHORTCUT_NAME + ".lnk")
    try:
        shell = win32com.client.Dispatch("WScript.Shell")
        shortcut = shell.CreateShortcut(shortcut_path)
        shortcut.TargetPath = bat_path
        shortcut.WorkingDirectory = os.path.dirname(bat_path)
        shortcut.IconLocation = "shell32.dll, 43"
        shortcut.WindowStyle = 7  # Minimized
        shortcut.Description = "TALOS Autonomous Research Daemon (24/7)" + (
            (" - profile: " + profile_name) if profile_name else ""
        )
        shortcut.save()
    except Exception as e:
        print(f"  [WARN] Could not create Startup shortcut: {e}")
        return None

    print(f"  [OK] Startup shortcut created: {shortcut_path}")
    return shortcut_path


def persist_daemon_config(profile_name, strategy=None, sources=None):
    """Persist the daemon target (plus optional strategy and sources) into the
    isolated profile config.

    Scaffolds ``_profiles/<profile_name>/config.json`` from the root working
    copy when missing and records ``daemon_profile`` / ``daemon_autostart``,
    optionally together with ``daemon_network_strategy`` and
    ``daemon_target_sources``, so the boot-time daemon resolves a single
    source of truth scoped to the selected profile.

    Args:
        profile_name (str): Target research profile for the daemon.
        strategy (str, optional): Daemon network strategy to record.
        sources (list of str, optional): Daemon target sources to record.

    Returns:
        str | None: Absolute path to the persisted config, or None on failure.
    """
    try:
        from src.core.profile_manager import ProfileManager
        pm = ProfileManager()
        profile_dir = pm.get_profiles_dir() / profile_name
        profile_dir.mkdir(parents=True, exist_ok=True)
        cfg_path = profile_dir / "config.json"
        if not cfg_path.exists():
            src = pm.root / "config.json"
            if not src.exists():
                src = pm.root / "config.template.json"
            if src.exists():
                import shutil
                shutil.copy2(str(src), str(cfg_path))
        cfg = {}
        if cfg_path.exists():
            try:
                cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
            except Exception:
                cfg = {}
        cfg["daemon_profile"] = profile_name
        cfg["daemon_autostart"] = True
        if strategy:
            cfg["daemon_network_strategy"] = strategy
        if sources is not None:
            cfg["daemon_target_sources"] = sources
        cfg_path.write_text(
            json.dumps(cfg, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"  [OK] Daemon configuration persisted: {cfg_path}")
        return str(cfg_path)
    except Exception as e:
        print(f"  [WARN] Could not persist daemon config into '{profile_name}': {e}")
        return None


def main():
    """Interactive autostart provisioning entry point.

    Profile selection is the FIRST mandatory prompt. On cancel the function
    exits cleanly without modifying any autostart state; otherwise it persists
    the selected target and installs the Windows Startup shortcut.

    Returns:
        str | None: Shortcut path, boot batch path, or None when cancelled.
    """
    target_profile = select_daemon_profile()
    if target_profile is None:
        print("  [CANCELLED] No profile selected -- autostart left unchanged.")
        return None
    persist_daemon_config(target_profile)
    result = install_windows_autostart(profile_name=target_profile)
    print(f"  [OK] TALOS daemon autostart configured for profile: {target_profile}")
    return result


if __name__ == "__main__":
    main()