# -*- coding: utf-8 -*-
"""
Module: daemon_autostart.py
Project: TALOS v5.18.3
Description:
    Windows OS autostart orchestrator for the TALOS 24/7 autonomous daemon.
    Generates a self-contained boot batch script (talos_daemon_boot.bat) that
    provisions the conda environment, conditionally starts the local Fast Edge
    CPU server, and launches the daemon. It then registers a Windows
    Startup-folder shortcut (via pywin32 Shell COM) so the daemon survives
    reboots with a minimized console and a system icon.

    v5.18.2 adds an interactive research-profile target selector: the operator
    chooses which profile the 24/7 daemon activates on boot, and the selected
    profile is embedded as a ``--profile <name>`` argument in both the boot
    batch script and the Startup shortcut so the daemon boots into the correct
    isolated workspace SSOT.

    v5.18.3 confirms this selector as the canonical daemon-profile provisioning
    path: the selected profile is embedded into the generated boot batch and
    Startup shortcut, and the daemon banner and execution dynamically
    synchronize to it via ``talos_service.py --profile <name>``.

    Key design decisions:
    - The generated .bat is human-auditable and lives at the project root.
    - pywin32 (win32com.client) is imported lazily inside the installer so
      this module remains importable on non-Windows platforms.
    - All shell operations are wrapped in try/except so a missing dependency
      or a missing Startup folder degrades gracefully with a clear message.

Dependencies:
    - os, pathlib: Filesystem and path resolution.
    - win32com.client (pywin32): Windows Shell COM shortcut creation (lazy).
"""
import os
import sys
from pathlib import Path


CPU_SERVER_PORT = 11435
SHORTCUT_NAME = "TALOS Autonomous Daemon"


def _project_root():
    """Resolve the absolute project root (parent of src/)."""
    return str(Path(__file__).resolve().parent.parent.parent)


def generate_boot_batch(profile_name=None):
    """Generate talos_daemon_boot.bat in the project root.

    The batch script sets a clean console, starts the local Fast Edge CPU
    server (port 11435) when the hardware strategy requires local CPU
    inference, and launches the daemon. All Python invocations use the
    absolute path of the current interpreter (sys.executable, quoted) so the
    correct conda environment is always used without relying on PATH.

    When ``profile_name`` is supplied (v5.18.2), a ``--profile <name>``
    argument is appended to the daemon invocation so the boot-time daemon
    activates the operator-selected research profile SSOT.

    Args:
        profile_name (str, optional): Target research profile for the daemon.

    Returns:
        str: Absolute path to the generated batch script.
    """
    root = _project_root()
    bat_path = os.path.join(root, "talos_daemon_boot.bat")
    py = '"' + sys.executable + '"'
    lines = [
        "@echo off",
        "mode con: cols=120 lines=30",
        "title TALOS Autonomous Research Daemon",
        'cd /d "%~dp0"',
        "",
        "REM -------------------------------------------------------------------",
        "REM TALOS Daemon Boot Script (generated by src/utils/daemon_autostart.py)",
        "REM -------------------------------------------------------------------",
        "",
        "REM 1. Start the local Fast Edge CPU server (port " + str(CPU_SERVER_PORT) + ") when",
        "REM    the hardware strategy needs local CPU inference.",
        'findstr /i "TALOS_HARDWARE_STRATEGY=.*cpu_gpu_split" "%~dp0.env" >nul 2>&1',
        'if %ERRORLEVEL%==0 start /B "" ' + py + ' -m llama_cpp.server --port ' + str(CPU_SERVER_PORT),
        'findstr /i "TALOS_HARDWARE_STRATEGY=.*cpu_only" "%~dp0.env" >nul 2>&1',
        'if %ERRORLEVEL%==0 start /B "" ' + py + ' -m llama_cpp.server --port ' + str(CPU_SERVER_PORT),
        "",
        "REM 2. Launch the 24/7 autonomous research daemon.",
        py + ' src/ai/drl/talos_service.py' + (
            ' --profile ' + profile_name if profile_name else ''
        ),
    ]
    with open(bat_path, "w", encoding="utf-8", newline="") as f:
        f.write(os.linesep.join(lines) + os.linesep)
    return bat_path


def select_daemon_profile():
    """Prompt the operator to choose the target research profile for the daemon.

    Queries ``ProfileManager().list_profiles()`` and renders a questionary
    select prompt defaulting to the current active profile. When no profiles
    exist, the active profile is used; when questionary is unavailable (for
    example a headless boot), the active profile is returned as-is.

    Returns:
        str: The selected profile name (never None).
    """
    try:
        from src.core.profile_manager import ProfileManager
        pm = ProfileManager()
        profiles = pm.list_profiles()
        active = pm.get_active_profile_name()
    except Exception:
        return "default"

    if not profiles:
        return active
    if active and active not in profiles:
        profiles.insert(0, active)

    try:
        import questionary
        choice = questionary.select(
            "Select the target research profile for the 24/7 background daemon:",
            choices=profiles,
            default=active,
        ).ask()
        return choice or active
    except Exception:
        return active


def install_windows_autostart(profile_name=None):
    """Install the TALOS daemon into the Windows Startup folder.

    Generates talos_daemon_boot.bat and creates a .lnk shortcut named
    "TALOS Autonomous Daemon" in the user's Startup folder with a system
    icon (shell32.dll) and a minimized window style. When ``profile_name``
    is supplied (v5.18.2), the selected research profile is embedded as a
    ``--profile <name>`` argument in both the boot batch and the shortcut.

    Args:
        profile_name (str, optional): Target research profile for the daemon.

    Returns:
        str | None: Path to the created shortcut, the boot batch path if the
            shortcut could not be created, or None on failure.
    """
    bat_path = generate_boot_batch(profile_name=profile_name)
    try:
        import win32com.client
    except ImportError:
        print("  [WARN] pywin32 not installed -- Startup shortcut not created.")
        print(f"  [INFO] Boot script generated at: {bat_path}")
        return None

    appdata = os.environ.get("APPDATA", "")
    startup_dir = os.path.join(
        appdata, "Microsoft", "Windows", "Start Menu", "Programs", "Startup")
    if not appdata or not os.path.isdir(os.path.dirname(startup_dir)):
        print("  [WARN] Startup folder not found -- shortcut not created.")
        return bat_path

    shortcut_path = os.path.join(startup_dir, SHORTCUT_NAME + ".lnk")
    try:
        shell = win32com.client.Dispatch("WScript.Shell")
        shortcut = shell.CreateShortcut(shortcut_path)
        shortcut.TargetPath = bat_path
        shortcut.WorkingDirectory = os.path.dirname(bat_path)
        shortcut.IconLocation = "shell32.dll, 43"
        shortcut.WindowStyle = 7  # Minimized
        shortcut.Description = "TALOS Autonomous Research Daemon (24/7)" + (
            (" - profile: " + profile_name) if profile_name else ""
        )
        shortcut.save()
    except Exception as e:
        print(f"  [WARN] Could not create Startup shortcut: {e}")
        return None

    print(f"  [OK] Startup shortcut created: {shortcut_path}")
    return shortcut_path


if __name__ == "__main__":
    profile_name = select_daemon_profile()
    install_windows_autostart(profile_name=profile_name)