# -*- coding: utf-8 -*-
"""
Module: daemon_autostart.py
Project: TALOS v5.10.6
Description:
    Windows OS autostart orchestrator for the TALOS 24/7 autonomous daemon.
    Generates a self-contained boot batch script (talos_daemon_boot.bat) that
    provisions the conda environment, conditionally starts the local Fast Edge
    CPU server, and launches the daemon. It then registers a Windows
    Startup-folder shortcut (via pywin32 Shell COM) so the daemon survives
    reboots with a minimized console and a system icon.

    Key design decisions:
    - The generated .bat is human-auditable and lives at the project root.
    - pywin32 (win32com.client) is imported lazily inside the installer so
      this module remains importable on non-Windows platforms.
    - All shell operations are wrapped in try/except so a missing dependency
      or a missing Startup folder degrades gracefully with a clear message.

Dependencies:
    - os, pathlib: Filesystem and path resolution.
    - win32com.client (pywin32): Windows Shell COM shortcut creation (lazy).
"""
import os
import sys
from pathlib import Path


CPU_SERVER_PORT = 11435
SHORTCUT_NAME = "TALOS Autonomous Daemon"


def _project_root():
    """Resolve the absolute project root (parent of src/)."""
    return str(Path(__file__).resolve().parent.parent.parent)


def generate_boot_batch():
    """Generate talos_daemon_boot.bat in the project root.

    The batch script sets a clean console, starts the local Fast Edge CPU
    server (port 11435) when the hardware strategy requires local CPU
    inference, and launches the daemon. All Python invocations use the
    absolute path of the current interpreter (sys.executable, quoted) so the
    correct conda environment is always used without relying on PATH.

    Returns:
        str: Absolute path to the generated batch script.
    """
    root = _project_root()
    bat_path = os.path.join(root, "talos_daemon_boot.bat")
    py = '"' + sys.executable + '"'
    lines = [
        "@echo off",
        "mode con: cols=120 lines=30",
        "title TALOS Autonomous Research Daemon",
        'cd /d "%~dp0"',
        "",
        "REM -------------------------------------------------------------------",
        "REM TALOS Daemon Boot Script (generated by src/utils/daemon_autostart.py)",
        "REM -------------------------------------------------------------------",
        "",
        "REM 1. Start the local Fast Edge CPU server (port " + str(CPU_SERVER_PORT) + ") when",
        "REM    the hardware strategy needs local CPU inference.",
        'findstr /i "TALOS_HARDWARE_STRATEGY=.*cpu_gpu_split" "%~dp0.env" >nul 2>&1',
        'if %ERRORLEVEL%==0 start /B "" ' + py + ' -m fermion serve --port ' + str(CPU_SERVER_PORT),
        'findstr /i "TALOS_HARDWARE_STRATEGY=.*cpu_only" "%~dp0.env" >nul 2>&1',
        'if %ERRORLEVEL%==0 start /B "" ' + py + ' -m fermion serve --port ' + str(CPU_SERVER_PORT),
        "",
        "REM 2. Launch the 24/7 autonomous research daemon.",
        py + ' src/ai/drl/talos_service.py',
    ]
    with open(bat_path, "w", encoding="utf-8", newline="") as f:
        f.write(os.linesep.join(lines) + os.linesep)
    return bat_path


def install_windows_autostart():
    """Install the TALOS daemon into the Windows Startup folder.

    Generates talos_daemon_boot.bat and creates a .lnk shortcut named
    "TALOS Autonomous Daemon" in the user's Startup folder with a system
    icon (shell32.dll) and a minimized window style.

    Returns:
        str | None: Path to the created shortcut, the boot batch path if the
            shortcut could not be created, or None on failure.
    """
    bat_path = generate_boot_batch()
    try:
        import win32com.client
    except ImportError:
        print("  [WARN] pywin32 not installed -- Startup shortcut not created.")
        print(f"  [INFO] Boot script generated at: {bat_path}")
        return None

    appdata = os.environ.get("APPDATA", "")
    startup_dir = os.path.join(
        appdata, "Microsoft", "Windows", "Start Menu", "Programs", "Startup")
    if not appdata or not os.path.isdir(os.path.dirname(startup_dir)):
        print("  [WARN] Startup folder not found -- shortcut not created.")
        return bat_path

    shortcut_path = os.path.join(startup_dir, SHORTCUT_NAME + ".lnk")
    try:
        shell = win32com.client.Dispatch("WScript.Shell")
        shortcut = shell.CreateShortcut(shortcut_path)
        shortcut.TargetPath = bat_path
        shortcut.WorkingDirectory = os.path.dirname(bat_path)
        shortcut.IconLocation = "shell32.dll, 43"
        shortcut.WindowStyle = 7  # Minimized
        shortcut.Description = "TALOS Autonomous Research Daemon (24/7)"
        shortcut.save()
    except Exception as e:
        print(f"  [WARN] Could not create Startup shortcut: {e}")
        return None

    print(f"  [OK] Startup shortcut created: {shortcut_path}")
    return shortcut_path


if __name__ == "__main__":
    install_windows_autostart()