# -*- coding: utf-8 -*-
#  Project TALOS
#  Copyright (C) 2026 Christos Smarlamakis
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  For commercial licensing, please contact the author.

"""
Module: grey_literature_miner.py
Project: TALOS v4.6.0

Description:
Εκτελεί αυτόνομη έρευνα ιστού εστιάζοντας στην "Γκρίζα Βιβλιογραφία"
(Grey Literature): GitHub repositories, Technical Reports, White Papers,
Datasets και Libraries που δεν υπάρχουν στις ακαδημαϊκές βάσεις.
Χρησιμοποιεί Google GenAI με Search Grounding.
"""
import os
import sys
import json
from datetime import datetime
from dotenv import load_dotenv
from google import genai
from google.genai.types import Tool, GenerateContentConfig, GoogleSearch
import questionary

# Προσθήκη path για imports
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

def load_config():
    path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'config.json'))
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def save_report(topic, content):
    # Αποθήκευση σε φάκελο 'reports/grey_literature'
    reports_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'reports', 'grey_literature'))
    os.makedirs(reports_dir, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    safe_topic = "".join([c if c.isalnum() else "_" for c in topic])[:50]
    filename = f"GreyLit_{safe_topic}_{timestamp}.md"
    filepath = os.path.join(reports_dir, filename)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(f"# Grey Literature Report: {topic}\n")
        f.write(f"_Automated Horizon Scan generated by TALOS on {datetime.now().strftime('%d-%m-%Y %H:%M')}_\n\n---\n\n")
        f.write(content)
    
    return filepath

def run_miner():
    print("\n--- GREY LITERATURE MINER (Web Horizon Scan) ---")
    load_dotenv()
    config = load_config()
    
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("ERROR: GEMINI_API_KEY not found.")
        return

    # 1. Ερώτηση στον Χρήστη
    research_topic = questionary.text(
        "Ποιο τεχνικό θέμα θέλεις να διερευνήσεις (GitHub, Tech Reports);",
        validate=lambda text: True if len(text.strip()) > 5 else "Please enter a valid topic."
    ).ask()
    
    if not research_topic: return
    
    # Optimize the search query with LLM
    print("  >> Optimizing search query...")
    search_query = research_topic
    try:
        from core.ai_manager import AIManager
        ai = AIManager(config)
        qprompt = f"Rewrite this research topic as a short English search query (5-8 keywords) for finding GitHub repos, datasets, and technical reports. Return ONLY the query, nothing else.\n\nTOPIC: {research_topic}"
        optimized = ai.analyze_generic_text(qprompt)
        if optimized and len(optimized.strip()) > 3:
            search_query = optimized.strip()
            print(f"  >> Query: {search_query}")
    except Exception as e:
        print(f"  >> Query optimization skipped: {e}")
    
    
    # Live web search (DuckDuckGo - free, no API key)
    print("  >> Searching the web...")
    web_results = ""
    try:
        from duckduckgo_search import DDGS  # or use: from ddgs import DDGS
        ddgs = DDGS()
        hits = list(ddgs.text(search_query, max_results=10))
        if hits:
            web_results = "\n**WEB SEARCH RESULTS:**\n" + "\n".join(
                f"- [{h['title']}]({h.get('href','#')}): {h.get('body','')[:200]}"
                for h in hits
            )
            print(f"  >> Found {len(hits)} web results")
    except Exception as e:
        print(f"  >> Web search unavailable: {e}")
    

    # 2. Επιστημονικό Prompt
    formatted_prompt = f"""
    **ROLE:** You are an expert Research Engineer.
    **TASK:** Perform a "Horizon Scan" / "Grey Literature Review" on the following topic:
    
    TOPIC: "{research_topic}"

    **OBJECTIVES:**
    Search for PRACTICAL resources on the open web that are often absent from academic databases. Focus on:
    1.  **Open Source Code:** GitHub/GitLab repositories (prioritize stars/activity).
    2.  **Datasets:** HuggingFace, Kaggle, University servers.
    3.  **Technical Reports:** White papers (NASA, DARPA, Big Tech), Standards (ISO, IEEE).
    4.  **Simulation Frameworks:** Tools relevant to the topic.

    **OUTPUT FORMAT (Markdown):**
    - **Executive Summary:** Brief technical overview.
    - **Key Repositories & Tools:** List with URLs and brief tech stack analysis.
    - **Datasets:** Available data for experiments.
    - **Emerging Trends:** Discussions in forums/blogs.
    
    
    - **References:** Direct URLs to all resources found.
    
    Provide the response in **Greek** (maintain English for technical terms/names).
    """

    print(f"\n🔮 Εκτέλεση σάρωσης ιστού. Αναμονή...\n")

    result_text = None

    try:
        client = genai.Client(api_key=api_key)
        print("  >> Gemini Search Grounding enabled")
        
        # BUGFIX: use correct config key "grey_research_model" with fallback
        model_id = config.get("grey_research_model", config.get("grey_literature_model", "gemini-flash-latest"))

        # Χρήση του google-genai SDK με Search Grounding
        response = client.models.generate_content(
            model=model_id,
            contents=formatted_prompt,
            config=GenerateContentConfig(
                tools=[Tool(google_search=GoogleSearch())],
                response_modalities=["TEXT"],
            )
        )
        
        if response.text:
            result_text = response.text
            print("\n--- Αποτελέσματα (Preview) ---")
            print(response.text[:500] + "...\n")
            
            # Έλεγχος για grounding metadata (πηγές)
            try:
                if response.candidates[0].grounding_metadata.search_entry_point:
                     print(f"🔎 Η έρευνα βασίστηκε σε πραγματικά δεδομένα Google Search.\n")
            except:
                pass
        else:
            print("\n⚠️ Δεν λήφθηκε κείμενο απάντησης.")

    except Exception as e:
        print(f"\n❌ Σφάλμα κατά την εκτέλεση: {e}")
        print("Συμβουλή: Βεβαιώσου ότι έχεις εγκαταστήσει το 'google-genai' (pip install google-genai).")
        result_text = None

    # Fallback: use AIManager if Gemini failed or unavailable
    if not result_text:
        print("  >> Falling back to AIManager...")
        try:
            from core.ai_manager import AIManager
            ai = AIManager(config)
            fb = formatted_prompt + "\n\n" + web_results if web_results else formatted_prompt
            result_text = ai.analyze_generic_text(fb)
        except Exception as e:
            print(f"  >> Fallback also failed: {e}")

    if result_text:
        print("\n--- Αποτελέσματα (Preview) ---")
        print(result_text[:500] + "...\n")
        filepath = save_report(research_topic, result_text)
        print(f"📄 Η αναφορά αποθηκεύτηκε: {filepath}")
    else:
        print("\n⚠️ Δεν λήφθηκε κείμενο απάντησης.")


if __name__ == "__main__":
    run_miner()