# -*- coding: utf-8 -*-
#  Project TALOS
#  Copyright (C) 2026 Christos Smarlamakis
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  For commercial licensing, please contact the author.

"""
Module: grey_literature_miner.py (v2.1 — Batch 3 hotfix)
Project: TALOS v5.3.6

Description:
    Autonomous web research agent focusing on "Grey Literature" — open source
    code, datasets, technical reports, and white papers not indexed by academic
    databases. Uses Google Gemini with Search Grounding for AI-powered web
    exploration, with DuckDuckGo as a fallback for live web search. The user's
    query is optimized by an LLM before searching, and results are saved as
    Markdown reports. Falls back to the AIManager multi-provider chain if
    Gemini is unavailable.

    v2.1 (Batch 3 hotfix):
    - DuckDuckGo import updated: tries the renamed `ddgs` package first,
      falls back to legacy `duckduckgo_search` (silences RuntimeWarning).
    - Missing GEMINI_API_KEY no longer hard-exits — the miner can run
      purely on the AIManager fallback chain (e.g. local Ollama) using
      DuckDuckGo web results as grounding.
"""
import os
import sys
import os, sys
_P = os.path.abspath(os.path.dirname(__file__))
while _P and not os.path.exists(os.path.join(_P, 'talos.py')):
    _P = os.path.dirname(_P)
if _P: sys.path.insert(0, _P)
import json
from datetime import datetime
from dotenv import load_dotenv
from google import genai
from google.genai.types import Tool, GenerateContentConfig, GoogleSearch
import questionary

def load_config():
    """Load the project configuration from config.json.

    Returns:
        dict: Configuration dictionary.
    """
    path = os.path.join(_P if _P else os.getcwd(), 'config.json')
    if not os.path.exists(path):
        path = os.path.join(_P if _P else os.getcwd(), 'config.template.json')
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def save_report(topic, content):
    """Save a grey literature report to the reports directory.

    Args:
        topic (str): Research topic for the filename.
        content (str): Markdown report content.

    Returns:
        str: Path to the saved report file.
    """
    reports_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'reports', 'grey_literature'))
    os.makedirs(reports_dir, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    safe_topic = "".join([c if c.isalnum() else "_" for c in topic])[:50]
    filename = f"GreyLit_{safe_topic}_{timestamp}.md"
    filepath = os.path.join(reports_dir, filename)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(f"# Grey Literature Report: {topic}\n")
        f.write(f"_Automated Horizon Scan generated by TALOS on {datetime.now().strftime('%d-%m-%Y %H:%M')}_\n\n---\n\n")
        f.write(content)

    return filepath


def run_miner():
    """Execute the grey literature mining workflow.

    Prompts the user for a research topic, optimizes the query via LLM,
    performs a live DuckDuckGo web search, then uses Gemini Search Grounding
    (with AIManager fallback) to generate a structured report.
    """
    print("\n--- GREY LITERATURE MINER (Web Horizon Scan) ---")
    load_dotenv()
    config = load_config()

    # v2.1: missing key is no longer fatal — Gemini Search Grounding is
    # simply skipped and the AIManager fallback chain (e.g. local Ollama)
    # handles the report generation using DuckDuckGo results.
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("  [WARN] GEMINI_API_KEY not found — Search Grounding disabled, using fallback providers.")

    research_topic = questionary.text(
        "What technical topic would you like to investigate (GitHub, Tech Reports)?",
        validate=lambda text: True if len(text.strip()) > 5 else "Please enter a valid topic."
    ).ask()

    if not research_topic: return

    print("  >> Optimizing search query...")
    search_query = research_topic
    try:
        from src.core.ai_manager import AIManager
        ai = AIManager(config)
        qprompt = f"Rewrite this research topic as a short English search query (5-8 keywords) for finding GitHub repos, datasets, and technical reports. Return ONLY the query, nothing else.\n\nTOPIC: {research_topic}"
        optimized = ai.analyze_generic_text(qprompt)
        if optimized and len(optimized.strip()) > 3:
            search_query = optimized.strip()
            print(f"  >> Query: {search_query}")
    except Exception as e:
        print(f"  >> Query optimization skipped: {e}")

    print("  >> Searching the web...")
    web_results = ""
    try:
        # v2.1: the package was renamed `duckduckgo_search` -> `ddgs`.
        # Try the new name first, fall back to the legacy one.
        try:
            from ddgs import DDGS
        except ImportError:
            from duckduckgo_search import DDGS
        ddgs = DDGS()
        hits = list(ddgs.text(search_query, max_results=10))
        if hits:
            web_results = "\n**WEB SEARCH RESULTS:**\n" + "\n".join(
                f"- [{h['title']}]({h.get('href','#')}): {h.get('body','')[:200]}"
                for h in hits
            )
            print(f"  >> Found {len(hits)} web results")
    except Exception as e:
        print(f"  >> Web search unavailable: {e}")

    formatted_prompt = f"""
    **ROLE:** You are an expert Research Engineer.
    **TASK:** Perform a "Horizon Scan" / "Grey Literature Review" on the following topic:

    TOPIC: "{research_topic}"

    **OBJECTIVES:**
    Search for PRACTICAL resources on the open web that are often absent from academic databases. Focus on:
    1.  **Open Source Code:** GitHub/GitLab repositories (prioritize stars/activity).
    2.  **Datasets:** HuggingFace, Kaggle, University servers.
    3.  **Technical Reports:** White papers (NASA, DARPA, Big Tech), Standards (ISO, IEEE).
    4.  **Simulation Frameworks:** Tools relevant to the topic.

    **OUTPUT FORMAT (Markdown):**
    - **Executive Summary:** Brief technical overview.
    - **Key Repositories & Tools:** List with URLs and brief tech stack analysis.
    - **Datasets:** Available data for experiments.
    - **Emerging Trends:** Discussions in forums/blogs.
    - **References:** Direct URLs to all resources found.

    Provide the response in **Greek** (maintain English for technical terms/names).
    """

    print(f"\nExecuting web scan. Please wait...\n")

    result_text = None

    try:
        # v2.1: skip Gemini entirely when no API key is available.
        if not api_key:
            raise RuntimeError("No GEMINI_API_KEY — skipping Search Grounding.")
        client = genai.Client(api_key=api_key)
        print("  >> Gemini Search Grounding enabled")

        model_id = config.get("grey_research_model", config.get("grey_literature_model", "gemini-flash-latest"))

        response = client.models.generate_content(
            model=model_id,
            contents=formatted_prompt,
            config=GenerateContentConfig(
                tools=[Tool(google_search=GoogleSearch())],
                response_modalities=["TEXT"],
            )
        )

        if response.text:
            result_text = response.text
            print("\n--- Results (Preview) ---")
            print(response.text[:500] + "...\n")

            try:
                if response.candidates[0].grounding_metadata.search_entry_point:
                    print(f"Search based on real-time Google Search data.\n")
            except:
                pass
        else:
            print("\nNo text response received.")

    except Exception as e:
        print(f"\nError during execution: {e}")
        print("Tip: Ensure 'google-genai' is installed (pip install google-genai).")
        result_text = None

    if not result_text:
        print("  >> Falling back to AIManager...")
        try:
            from src.core.ai_manager import AIManager
            ai = AIManager(config)
            fb = formatted_prompt + "\n\n" + web_results if web_results else formatted_prompt
            result_text = ai.analyze_generic_text(fb)
        except Exception as e:
            print(f"  >> Fallback also failed: {e}")

    if result_text:
        print("\n--- Results (Preview) ---")
        print(result_text[:500] + "...\n")
        filepath = save_report(research_topic, result_text)
        print(f"Report saved: {filepath}")
    else:
        print("\nNo text response received.")


if __name__ == "__main__":
    run_miner()